### ISSUE TITLE
Copy Protection Additions

### ISSUE THREAD

**Issue by mnadareski** [SabreTools/BinaryObjectScanner#1]
*This has been migrated from the DICUI issue tracker*

This is a dumping ground for all known copy protections that are not detected by BurnOutSharp properly. For anyone commenting, please include the name of the disc, the name of the file, the protection that BurnOutSharp detected and the protection that ProtectionId detected. This will help keep track of things for better testing.

Known issues:
- No sector scanning
- Minor scanning of textfiles
- No scanning of archives - 7Z, RAR, PKZIP, ARC
- No internal key decryption for DVD, HD-DVD, BD, UHD-BD
    - DVD unhandled
    - HD-DVD unhandled
    - BD/UHD-BD unhandled
- The following protection schemes need to be verified in the real world due to a decrement operation used in the code:
    - SolidShield 2, SolidShield 2 + TAGES
    - TAGES
    - VOB ProtectCD/DVD

| Disc Name | File Name | DICUI | PiD | Reported By |
| ------------ | ----------- | ------ | ---- | -------------  |
| Wiggles (DE) | N/A | N/A | N/A (VOB Protect CD/DVD should be) | Kludge |

**Comment by TheRogueArchivist** [comment]
Many of these have already been addressed, so it may make more sense to just close this issue and report anything still remaining as separate issues.
