### ISSUE TITLE
nProtect GameGuard protection

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/BinaryObjectScanner#154]
File located on an alt of http://redump.org/disc/57758/ (Lineage: The Blood Pledge)

> [CONFIG]
> SERVER=www.nprotect.co.kr/service/ncsoft/nprotect.html
> REG_URL=http://www.nprotect.co.kr/member/ncsoft_register01.php

`nProtect GameGuard (sometimes called GG) is an anti-cheating rootkit developed by INCA Internet. It is widely installed in many online games to block possibly malicious applications and prevent common methods of cheating.`

**Comment by Flashfire42** [comment]
https://store.steampowered.com/app/1549250/UNDECEMBER/
Also apparently found on this game?

**Comment by TheRogueArchivist** [comment]
Though GameGuard detection has been added, I can't seem to find a trace of it on any "Lineage: The Blood Pledge" games in Redump? Will have to check more thoroughly later.
