### ISSUE TITLE
SecuROM (CAB) not detected

### ISSUE THREAD

**Issue by soxhi8** [SabreTools/BinaryObjectScanner#243]
Version 2.6.0 and up will not correctly detect SecuROM for one of my games. According to @mnadareski this is related to the previous removal of a CAB-library.

- Expected result (taken from 2.5.0):
```
[...]
D:CODEC\WMFDist.exe: Microsoft CAB SFX v7.01.00.3055
D:instmsia.exe: Microsoft CAB SFX v2.0.2600.2
D:instmsiw.exe: Microsoft CAB SFX v2.0.2600.2
D:MainApp.cab\Fellowship.exe: SecuROM 4.83.55.0030
Press enter to close the program...
```
- Actual result (2.6.0 up to current master):
```
[...]
D:\CODEC\WMFDist.exe: Microsoft CAB SFX v7.01.00.3055
D:\instmsia.exe: Microsoft CAB SFX v2.0.2600.2
D:\instmsiw.exe: Microsoft CAB SFX v2.0.2600.2
Press enter to close the program...
```

**Comment by mnadareski** [comment]
Another partial change that helps this situation: https://github.com/mnadareski/BurnOutSharp/commit/ecf97de4399df6fd70deef31a97305788e8ae514

**Comment by mnadareski** [comment]
MS-CAB is in a very poor state in general and is a known issue. This specific issue is covered by that.
