### ISSUE TITLE
Program abortion upon inaccessible directories and junctions

### ISSUE THREAD

**Issue by Feathered-Serpent** [SabreTools/BinaryObjectScanner#256]
Upon trying to let a whole disk drive being scanned (e.g. where one might install games), BurnOutSharp first stops at this:
`System.UnauthorizedAccessException: Access to the path 'C:\System Volume Information' is denied.`

Probably because the directory is owned from the Windows System account. But it's not only permissions who stop the program:
`System.UnauthorizedAccessException: Access to the path 'C:\Program Files\Gemeinsame Dateien' is denied.`

This is a junction to another directory:
`<JUNCTION>     Gemeinsame Dateien [C:\Program Files\Common Files]`

So how can I make the program just skip over these entries?

**Comment by mnadareski** [comment]
Current `SafeEnumerate` methods are the best we can do at this point.
