### ISSUE TITLE
Subdirectories of archives not being extracted

### ISSUE THREAD

**Issue by Feathered-Serpent** [SabreTools/BinaryObjectScanner#257]
While scanning I noticed, that not all files from (at least) 7z files are extracted.

The archive looks like this:
![grafik](https://github.com/mnadareski/BurnOutSharp/assets/72162369/ef6ff631-3cf6-4e0b-b382-f1b06a9aaca6)

Upon scanning it without --debug it just shows:
```
8,33%: C:\apps\audio\The GodFather\The GodFather v0.7.7z - Checking file
0,00%:  -
0,00%: \lame.ini - Checking file from archive
11,11%: \lame.ini -
11,11%: \lib.ini - Checking file from archive
22,22%: \lib.ini -
22,22%: \oggvorbis.ini - Checking file from archive
33,33%: \oggvorbis.ini -
33,33%: \tgf.chm - Checking file from archive
44,44%: \tgf.chm -
44,44%: \tgf.ini - Checking file from archive
55,56%: \tgf.ini -
55,56%: \tgf.mdb - Checking file from archive
66,67%: \tgf.mdb -
66,67%: \TheGodFather.exe - Checking file from archive
77,78%: \TheGodFather.exe -
77,78%: \Uninstall.exe - Checking file from archive
88,89%: \Uninstall.exe - NSIS v2.46
88,89%: \xaudio.dll - Checking file from archive
100,00%: \xaudio.dll -
9,72%: C:\apps\audio\The GodFather\The GodFather v0.7.7z -
```

with debug I get lots of messages like this one:
`System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Ezatoka\AppData\Local\Temp\42b3b7ed-76f2-43b3-8583-d2719cfad726\Lng\bulgarian.lng'.`

But of course the files are there in the 7z file:
![grafik](https://github.com/mnadareski/BurnOutSharp/assets/72162369/6584347b-3f04-489d-a118-4989ef7364a2)

**Comment by Feathered-Serpent** [comment]
rar archives also have this problem:
11,18%: C:\games\Istaria\resources_override\Tools\REShade Istaria + Starstipreset.rar - Checking file
`System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Ezatoka\AppData\Local\Temp\2272aaa6-9e9e-476b-b612-9f28a0f61a6f\reshade-shaders\README.md'.`

**Comment by mnadareski** [comment]
Is this still happening? A lot has changed in the underlying archive code since.

**Comment by mnadareski** [comment]
The cause of this was finally determined and fixed.
