### ISSUE TITLE
Unknown SafeDisc version

### ISSUE THREAD

**Issue by prklx2** [SabreTools/BinaryObjectScanner#282]
SafeDisc unknown version error. 

Disc has SafeDisc 4.
MPF version 3.1.0

```
I:\DrvMgt.dll: SafeDisc Unknown Version (Report this to us on GitHub)
I:\SECDRV.SYS: Macrovision Security Driver / Product Unknown (Report this to us on GitHub)
I:\Tsonic_Win.exe: Macrovision Protected Application, SafeDisc 4.00.000
```

**Comment by TheRogueArchivist** [comment]
Hello! What game is this on?

**Comment by prklx2** [comment]
Sonic Heroes for PC

**Comment by TheRogueArchivist** [comment]
Thank you! And would you happen to know if its on redump? For example, could it be http://redump.org/disc/34445/?

**Comment by prklx2** [comment]
It's currently not on Redump. I was about to send it's information there but I noticed this issue detecting the copy protection.

**Comment by TheRogueArchivist** [comment]
No problem, I think I've figured out what's going on! Can you confirm that drvmgt and secdev are both 0 bytes?

**Comment by prklx2** [comment]
Yes! They're both 0 bytes.

**Comment by TheRogueArchivist** [comment]
Perfect! Feel free to ignore those files then, so just report it as being SafeDisc 4.00.000. I've updated BOS to account for the possibility of those files being 0 bytes, so I'll close this issue! Thank you for reporting this bug 😁

**Comment by Sewer56** [comment]
Hi, I just came across this project.

To the best of my awareness, Sonic Heroes (USA) is `04.00.01`, not `04.00.00`.

You can detect SafeDisc v2 and above by searching for the string `BoG_ *90.0&!!  Yy>` 
(`42 6F 47 5F 20 2A 39 30 2E 30 26 21 21 20 20 59 79 3E`). 

This is usually found at offset 4052 in most EXEs, at the end of the padding after the NT Headers.
14 bytes after that signature, you will find the SafeDisc version, in Sonic Heroes' case, this is `04 00 00 00 00 00 00 00 01 00 00 00`

**Comment by mnadareski** [comment]
Hello, thanks for the input but we already do those things if you take a look at the code. The `BoG_` string is very well known, as are the section names.

**Comment by Sewer56** [comment]
Ah, I'm very tired, and didn't catch it, oopsie.
In any case, yeah, it's true, the US version of Heroes has an empty `secdrv.sys` and `drvmgt.dll`.

The Japanese PC version (extremely rare) has them non blank, and a SafeDisc version of `03.20.22`
