### ISSUE TITLE
Unable to detect SecuROM 7.35.0007

### ISSUE THREAD

**Issue by IcySon55** [SabreTools/BinaryObjectScanner#288]
BoS 3.1.0 was not able to detect SecuROM 7.35.0007 on Warhammer 40,000: Dawn of War: Soulstorm when scanning both the disc and the installed files on the hard drive.

**Comment by mnadareski** [comment]
@IcySon55 and @TheRogueArchivist it seems like this was taken care of?

**Comment by TheRogueArchivist** [comment]
Confirmed to be fixed.
