### ISSUE TITLE
System Shock 2 .mc files causing copy protection scan to hang.

### ISSUE THREAD

**Issue by Randy2727** [SabreTools/BinaryObjectScanner#292]
MPF hangs on the copy protection scan of a dump of System Shock 2 on the file `aracdyng_.mc` that is contained in the archive? `motions.crf`.

Testing an extracted `aracdyng_.mc` with BOS test.exe outputs `File format found: BSP`

[aracdyng_.zip](https://github.com/SabreTools/BinaryObjectScanner/files/14799921/aracdyng_.zip)

**Comment by mnadareski** [comment]
This is definitely a `BSP` file based on everything I can find internally. Unfortunately, the value that it's getting for the number of textures is `1065332325`, which seems a bit high.

**Comment by mnadareski** [comment]
For now, the serialization library will cut off if it runs past the end of the file instead of just trying to build blindly. Unfortunately, what this will likely need is a special bit of handling for BSP v30 files that are specialized for System Shock 2.

**Comment by mnadareski** [comment]
Newest BOS rolling release (https://github.com/SabreTools/BinaryObjectScanner/releases/tag/rolling) includes the changes above. Please test when possible.
