### ISSUE TITLE
Dark Projet II .mc file cause  copy protection scan to hang and fill RAM

### ISSUE THREAD

**Issue by eingrossfilou** [SabreTools/BinaryObjectScanner#302]
When scanning copy protection of a dump of Dark Project II: The Metal Age (or Thief II),  MPF 3.18 hangs on the file `\BS114002_.mc` in archive `THIEF2\RES\motions.crf `
In addition it MPF fills the RAM (It uses tens of GiB)

`BS114002_.mc` info returns 
```
File format found: BSP
```
Must be similar to #292

Here the problematic file extracted from `THIEF2\RES\motions.crf `: [BS114002_.zip](https://github.com/SabreTools/BinaryObjectScanner/files/15284298/BS114002_.zip)

**Comment by Deterous** [comment]
This same behavior was also reported (not via GitHub) to have occured with System Shock II on 3.1.8.
Since Thief II is by the same dev / has the same game engine as SS2, it will be the exact same error and file type as #292 but the latest version of SabreTools.Serialization has changed how it reacts to these files.

**Comment by mnadareski** [comment]
`.mc` files unfortunately share a first few bytes in common with most BSP files while being nowhere related. This issue did not broadly cause issues, so it was not focused on in the last set of changes that were required to fix much larger problms.

**Comment by mnadareski** [comment]
Newest BOS rolling release (https://github.com/SabreTools/BinaryObjectScanner/releases/tag/rolling) includes the changes above. Please test when possible.

**Comment by eingrossfilou** [comment]
A bit late for an feedback, but I successfully dump it today with MPF 3.7.1.
