### ISSUE TITLE
[Bug] Unable to extract folders in 7z archives

### ISSUE THREAD

**Issue by TheRogueArchivist** [SabreTools/BinaryObjectScanner#322]
When trying to scan 7z archives, BOS is unable to extract folders and their contents. When attempting to, it gives the error: 
``` Exception thrown: 'System.IO.DirectoryNotFoundException' in System.Private.CoreLib.dll ```

Also occurs with SFX archives using #321.

**Comment by mnadareski** [comment]
More information is needed. Please provide a full stacktrace as output by the debug build.

**Comment by TheRogueArchivist** [comment]
Fixed by 28ebc14fe1e5f10b251b8f820847073569904d33.
