### ISSUE TITLE
[Bug] MS-CABs not consistently extracted

### ISSUE THREAD

**Issue by TheRogueArchivist** [SabreTools/BinaryObjectScanner#66]
On some discs (Age of Empires III Disc 2), it seems that MS-CABs aren't extracted when doing a directory check (Ex. "./test F:"), and are only extracted (or show output of archive scanning) when scanning the file directly (Ex. "./test "F:\Disk2C~1.cab").

**Comment by mnadareski** [comment]
@SilasLaspada please check this with the latest commits

**Comment by mnadareski** [comment]
This has been a long-running and well-known issue that has been "fixed" by using a third-party library that only works on certain platforms.
