### ISSUE TITLE
Detecting CD-COPS String in CDCOPS.DLL

### ISSUE THREAD

**Issue by Flashfire42** [SabreTools/BinaryObjectScanner#88]
![image](https://user-images.githubusercontent.com/40415824/157557462-5c0fc757-ad77-4534-a191-c0a718fe3ac3.png)
In 2 of the 3 samples I have been able to examine so far of the CDCOPS.DLL this string is at the same offset every time in the third sample it is off by 1 but the string is still there. The files are all NEEXE according to virustotal which may make things more difficult to parse. If I get further info on the dll I will update this issue. They are also reportably all 16bit windows applications

**Comment by TheRogueArchivist** [comment]
I can confirm that this check is now present and functional.
